### ISSUE TITLE
This is not really an issue but a neat little CSS hack I figured out that avoids having to use any script to resolve this annoying Chrome bug

### ISSUE THREAD

**Issue by riomyers** [Stanko/mobile-chrome-vh-fix#4]
so let's say you have an element using vh for example: 

```
div {
  height: 100%;
  min-height: 100vh;
}
```

You can actually resolve the problem by just adding an eternal transition delay to the min-height using CSS

```
div {
  height: 100%;
  min-height: 100vh;
  transition: min-height 999999s;
}
```
What this does is it ensures that the height adjustment never actually happens when you're scrolling on Chrome because it takes 999999s for the min-height transition to complete so you never see the element adjust when the top or bottom scrollbars on Chrome mobile disappear, a bit hacky but it works.

**Comment by adi-works** [comment]
I've seen this fix before. So annoying we have to resort to such hacks. I honestly prefer the JS solution, despite no hardware acceleration.

**Comment by riomyers** [comment]
it is annoying indeed, chrome should just make their mobile browser more efficient

**Comment by jamiemitchell** [comment]
Although it doesn't resize on device orientation change. It has been the simplest fix I found so far.
